/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CategoryCategoryNameRouteImport } from './routes/category.$categoryName'
import { Route as AdminCreatorRouteImport } from './routes/admin/creator'
import { Route as AdminCategoryRouteImport } from './routes/admin/category'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CategoryCategoryNameRoute = CategoryCategoryNameRouteImport.update({
  id: '/category/$categoryName',
  path: '/category/$categoryName',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreatorRoute = AdminCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryRoute = AdminCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRoute
  '/admin/creator': typeof AdminCreatorRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/category': typeof AdminCategoryRoute
  '/admin/creator': typeof AdminCreatorRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRoute
  '/admin/creator': typeof AdminCreatorRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/category'
    | '/admin/creator'
    | '/category/$categoryName'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/category'
    | '/admin/creator'
    | '/category/$categoryName'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/category'
    | '/admin/creator'
    | '/category/$categoryName'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CategoryCategoryNameRoute: typeof CategoryCategoryNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/category/$categoryName': {
      id: '/category/$categoryName'
      path: '/category/$categoryName'
      fullPath: '/category/$categoryName'
      preLoaderRoute: typeof CategoryCategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/creator': {
      id: '/admin/creator'
      path: '/creator'
      fullPath: '/admin/creator'
      preLoaderRoute: typeof AdminCreatorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category': {
      id: '/admin/category'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoryRoute: typeof AdminCategoryRoute
  AdminCreatorRoute: typeof AdminCreatorRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoryRoute: AdminCategoryRoute,
  AdminCreatorRoute: AdminCreatorRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CategoryCategoryNameRoute: CategoryCategoryNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
